### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by Blasg2** [Michael-wigontherun/ESLifyEverything#25]
AggregateException. Please report to GitHub with log file.
System.AggregateException: One or more errors occurred. (Could not find a part of the path 'F:\SteamLibrary\steamapps\common\Skyrim Special Edition\ESLifyEverything\OverrideSourceCode'.)
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'F:\SteamLibrary\steamapps\common\Skyrim Special Edition\ESLifyEverything\OverrideSourceCode'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at ESLifyEverything.ESLify.ExtractScripts() in C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\ESLifyScript.cs:line 139
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ESLifyEverything.ESLify.StartScriptESLify(String logName, HashSet`1 startupError) in C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\ESLify.cs:line 232
   at ESLifyEverything.Program.Main(String[] args) in C:\Modding\SkyrimSE\ESLifyEverything\ESLifyEverything\Program.cs:line 45
One or more errors occurred. (Could not find a part of the path 'F:\SteamLibrary\steamapps\common\Skyrim Special Edition\ESLifyEverything\OverrideSourceCode'.)
--------------------------------------------
[ESLifyEverything_Log.txt](https://github.com/Michael-wigontherun/ESLifyEverything/files/13956738/ESLifyEverything_Log.txt)
-------------------------------------------------------------------------------------

**Comment by Michael-wigontherun** [comment]
Add a folder called OverrideSourceCode to the eslifyeverthing folder
